[package]
name = "kv_store"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.1"
env_logger = "0.11.8"
log = "0.4.27"
parking_lot = "0.12.3"
prost = "0.13.5" # 编码解码
thiserror = "2.0.12"
